version: "2"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      security_network:
        ipv4_address: 172.18.2.20

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.0
    depends_on: 
      - elasticsearch
    ports:
      - 5045:5045
    volumes:
      - ./logstash/config_files/:/etc/logstash/conf.d/:ro
    command: logstash -f /etc/logstash/conf.d/
    networks:
      security_network:
        ipv4_address: 172.18.2.21

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks:
      security_network:
        ipv4_address: 172.18.2.22

networks:
  security_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.2.0/24
          gateway: 172.18.2.2