version: "2"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment: 
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=sec-testing
      - discovery.seed_hosts=127.0.0.1

    volumes:
      - sec_esdata01:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    networks:
      security_network:
        ipv4_address: 172.18.2.20
    ports: 
      - 9200:9200
      - 9300:9300

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.0
    depends_on: 
      - elasticsearch
    ports:
      - 5045:5045
    volumes:
      - ./logstash/config_files/:/etc/logstash/conf.d/:ro
    command: logstash -f /etc/logstash/conf.d/
    networks:
      security_network:
        ipv4_address: 172.18.2.21

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    environment:
      - elasticsearch.hosts=172.18.2.20
      - xpack.security.enabled=false
    networks:
      security_network:
        ipv4_address: 172.18.2.22

volumes:
  sec_esdata01:
    driver: local

networks:
  security_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.2.0/24
          gateway: 172.18.2.2